datasets:
  - name: glove50
    metric: l2
  - name: random
    metric: l2

output_dir: /storage/ice-shared/cs8903onl/vectordb-retrieval/results
data_dir: /storage/ice-shared/cs8903onl/vectordb-retrieval/datasets

n_queries: 100
topk: 10
repeat: 1
algorithms:
  exact:
    type: ExactSearch
#  hnsw:
#    type: HNSW
#    M: 16
#    efConstruction: 200
#    efSearch: 100
seed: 42
output_prefix: benchmark
