#> random and glove50 are stored as Euclidean vectors, so their configs keep metric: l2 (with L2-compatible indexers/searchers). MS MARCO’s Cohere embeddings belong on the unit sphere and are almost always searched with cosine similarity (1 – dot product). Forcing everything to use the same metric would mean either:
#
#  - Pretending the MS MARCO embeddings are best handled by L2—which would hurt their recall, or
#  - Converting the other datasets to cosine and swapping their index/search settings.
#

indexers:
  brute_force_l2:
    type: BruteForceIndexer
    metric: l2
  brute_force_cosine:
    type: BruteForceIndexer
    metric: cosine
  hnsw_l2:
    type: HNSWIndexer
    M: 16
    efConstruction: 200
    efSearch: 100
    metric: l2
  hnsw_cosine:
    type: HNSWIndexer
    M: 16
    efConstruction: 200
    efSearch: 100
    metric: cosine
  faiss_ivf_l2:
    type: FaissIVFIndexer
    index_type: IVF100,Flat
    metric: l2
    nprobe: 10
  faiss_ivf_cosine:
    type: FaissIVFIndexer
    index_type: IVF100,Flat
    metric: cosine
    nprobe: 10
  faiss_ivf_pq_l2:
    type: FaissFactoryIndexer
    index_key: IVF256,PQ64
    metric: l2
    nprobe: 24
  faiss_ivf_pq_l2_glove:
    type: FaissFactoryIndexer
    index_key: IVF256,PQ50
    metric: l2
    nprobe: 24
  faiss_ivf_pq_cosine:
    type: FaissFactoryIndexer
    index_key: IVF256,PQ64
    metric: cosine
    nprobe: 48
  faiss_ivf_sq8_l2:
    type: FaissFactoryIndexer
    index_key: IVF256,SQ8
    metric: l2
    nprobe: 24
  faiss_ivf_sq8_cosine:
    type: FaissFactoryIndexer
    index_key: IVF256,SQ8
    metric: cosine
    nprobe: 48
  faiss_pq_l2:
    type: FaissFactoryIndexer
    index_key: PQ64
    metric: l2
  faiss_pq_cosine:
    type: FaissFactoryIndexer
    index_key: PQ64
    metric: cosine
  faiss_pq_l2_glove:
    type: FaissFactoryIndexer
    index_key: PQ50
    metric: l2
  lsh_l2:
    type: LSHIndexer
    metric: l2
    num_tables: 12
    hash_size: 18
    bucket_width: 4.0
    seed: 42
  lsh_cosine:
    type: LSHIndexer
    metric: cosine
    num_tables: 12
    hash_size: 18
    seed: 42

searchers:
  linear_l2:
    type: LinearSearcher
    metric: l2
  linear_cosine:
    type: LinearSearcher
    metric: cosine
  faiss_l2:
    type: FaissSearcher
    metric: l2
    nprobe: 10
  faiss_cosine:
    type: FaissSearcher
    metric: cosine
    nprobe: 32
  faiss_l2_highprobe:
    type: FaissSearcher
    metric: l2
    nprobe: 24
  faiss_cosine_highprobe:
    type: FaissSearcher
    metric: cosine
    nprobe: 48
  lsh_search_l2:
    type: LSHSearcher
    metric: l2
    candidate_multiplier: 8.0
    fallback_to_bruteforce: true
  lsh_search_cosine:
    type: LSHSearcher
    metric: cosine
    candidate_multiplier: 8.0
    fallback_to_bruteforce: true

algorithms:
  exact:
    indexer_ref: brute_force_l2
    searcher_ref: linear_l2
    metric: l2
  hnsw:
    indexer_ref: hnsw_l2
    searcher_ref: faiss_l2
    metric: l2
  ivf_flat:
    indexer_ref: faiss_ivf_l2
    searcher_ref: faiss_l2
    metric: l2
  ivf_pq:
    indexer_ref: faiss_ivf_pq_l2
    searcher_ref: faiss_l2_highprobe
    metric: l2
  ivf_sq8:
    indexer_ref: faiss_ivf_sq8_l2
    searcher_ref: faiss_l2_highprobe
    metric: l2
  pq:
    indexer_ref: faiss_pq_l2
    searcher_ref: faiss_l2_highprobe
    metric: l2
  lsh:
    indexer_ref: lsh_l2
    searcher_ref: lsh_search_l2
    metric: l2
datasets:
  - name: random
    metric: l2
#  - name: sift1m
#    metric: l2
  - name: glove50
    metric: l2
    algorithms:
      ivf_pq:
        indexer_ref: faiss_ivf_pq_l2_glove
      pq:
        indexer_ref: faiss_pq_l2_glove
  - name: msmarco
    metric: cosine
    dataset_options:
      use_preembedded: true
      preembedded_passage_dir: /storage/ice-shared/cs8903onl/vectordb-retrieval/datasets/msmarco_pre_embeded/passages_parquet
      preembedded_query_dir: /storage/ice-shared/cs8903onl/vectordb-retrieval/datasets/msmarco_pre_embeded/queries_parquet
      passage_embedding_column: emb
      query_embedding_column: emb
      passage_id_column: _id
      query_relevance_column: top1k_passage_ids
      query_relevance_offsets_column: top1k_offsets
      relevance_candidates_limit: 64
#      uncomment below to only process a limited size
      base_limit: 300000
      query_limit: 1000
      ground_truth_k: 1000
      cache_dir: /storage/ice-shared/cs8903onl/vectordb-retrieval/results/cache
    algorithms:
      exact:
        indexer_ref: brute_force_cosine
        searcher_ref: linear_cosine
      hnsw:
        indexer_ref: hnsw_cosine
        searcher_ref: faiss_cosine
      ivf_flat:
        indexer_ref: faiss_ivf_cosine
        searcher_ref: faiss_cosine
      ivf_pq:
        indexer_ref: faiss_ivf_pq_cosine
        searcher_ref: faiss_cosine_highprobe
      ivf_sq8:
        indexer_ref: faiss_ivf_sq8_cosine
        searcher_ref: faiss_cosine_highprobe
      pq:
        indexer_ref: faiss_pq_cosine
        searcher_ref: faiss_cosine_highprobe
      lsh:
        indexer_ref: lsh_cosine
        searcher_ref: lsh_search_cosine
        metric: cosine
output_dir: /storage/ice-shared/cs8903onl/vectordb-retrieval/results
data_dir: /storage/ice-shared/cs8903onl/vectordb-retrieval/datasets
n_queries: 1000
output_prefix: benchmark
repeat: 2
seed: 42
topk: 1000
