algorithms:
  exact:
    metric: l2
    type: ExactSearch
  hnsw:
    M: 16
    efConstruction: 200
    efSearch: 100
    metric: l2
    type: HNSW
  ivf_flat:
    index_type: IVF100,Flat
    metric: l2
    nprobe: 10
    type: ApproximateSearch
datasets:
- random
- sift1m
- glove50
n_queries: 1000
output_prefix: benchmark
repeat: 1
seed: 42
topk: 100
