datasets:
  - name: glove50
    metric: l2
  - name: random
    metric: l2
n_queries: 100
topk: 10
repeat: 1
algorithms:
  exact:
    type: ExactSearch
#  hnsw:
#    type: HNSW
#    M: 16
#    efConstruction: 200
#    efSearch: 100
seed: 42
output_prefix: benchmark
