algorithms:
  exact:
    type: ExactSearch
  hnsw:
    M: 16
    efConstruction: 200
    efSearch: 100
    type: HNSW
  ivf_flat:
    index_type: IVF100,Flat
    nprobe: 10
    type: ApproximateSearch
datasets:
  - name: random
    metric: l2
  - name: sift1m
    metric: l2
  - name: glove50
    metric: l2
n_queries: 1000
output_prefix: benchmark
repeat: 1
seed: 42
topk: 100
